version: 2

sources:
    - name: my_dbt_db
      schema: my_dbt_db

      tables:
        - name: raw_customers


version: 2

models:
    - name: stg_customers
      columns:
        - name: customer_id
        - name: customer_name